#api网关
server:
  port: 6501
spring:
  application:
    name: zuulService
  boot:
      admin:
        client:
          url: http://192.168.200.135:7000
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
       defaultZone: http://192.168.200.85:6801/eureka/,http://192.168.200.135:6802/eureka/,http://192.168.200.136:6803/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
     env:
       enabled: true
zuul:
  host:
    connectTimeoutMillis: 60000
    socket-timeout-millis: 60000
  routes:
    api-user-route:
      # 访问/user/开头的路由转发到会员服务;
      path: /user/**
      serviceId: userimp
    api-order-route:
      # 访问/order/开头的转发的order服务; 默认支持feibin 支持自动负载均衡
      path: /order/**
      serviceId: orderimp
    #匹配/github/直接重定向到https://github.com/
    github:
      path: /github/**
      url: https://github.com/
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 60000
